mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.localhost'
    - '*.arpa'
    - 'time.*.com'
    - 'ntp.*.com'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '*.n.n.sv.netsuite.com'
  use-hosts: true
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxy-providers:
  BBN:
    type: http
    url: "𝐃𝐚́𝐧 𝐒𝐮𝐛"
    path: ./proxies/bbn.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
proxy-groups:
  - name: 𝐁𝐨𝐁𝐢𝐞𝐧𝐍𝐠𝐚
    type: select
    proxies:
      - DIRECT
      - 𝐀𝐮𝐭𝐨 𝐒𝐞𝐥𝐞𝐜𝐭
    use:
      - BBN
    icon: 'https://anhh.vercel.app/csa.png'
  - name: 𝐀𝐮𝐭𝐨 𝐒𝐞𝐥𝐞𝐜𝐭
    type: url-test
    use:
      - BBN
    url: 'https://www.gstatic.com/generate_204'
    interval: 300
    tolerance: 30
    icon: 'https://anhh.vercel.app/rocket.png'
  - name: 𝐕𝐢𝐞𝐭𝐍𝐚𝐦
    type: select
    use:
      - BBN
    filter: "🇻🇳"
    icon: https://anhh.vercel.app/vietnam.png
  - name: 𝐒𝐢𝐧𝐠𝐚𝐩𝐨𝐫𝐞
    type: select
    use:
      - BBN
    filter: "🇸🇬"
    icon: https://anhh.vercel.app/singapore.png
  - name: 𝐉𝐚𝐩𝐚𝐧
    type: select
    use:
      - BBN
    filter: "🇯🇵"
    icon: https://anhh.vercel.app/japan.png
  - name: 𝐇𝐨𝐧𝐠𝐊𝐨𝐧𝐠
    type: select
    use:
      - BBN
    filter: "🇭🇰"
    icon: https://anhh.vercel.app/hongkong.png
  - name: 𝐔𝐒𝐀
    type: select
    use:
      - BBN
    filter: "🇺🇸"
    icon: https://anhh.vercel.app/hoaky.png
rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-KEYWORD,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - DOMAIN-SUFFIX,home,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,𝐁𝐨𝐁𝐢𝐞𝐧𝐍𝐠𝐚
